export const ROLES = {
  ADMIN:   'ADMIN',
  MANAGER: 'MANAGER',
  VIEWER:  'VIEWER',
};

export const PERMISSIONS = {
  // Products
  PRODUCT_VIEW:   [ROLES.ADMIN, ROLES.MANAGER, ROLES.VIEWER],
  PRODUCT_CREATE: [ROLES.ADMIN, ROLES.MANAGER],
  PRODUCT_EDIT:   [ROLES.ADMIN, ROLES.MANAGER],
  PRODUCT_DELETE: [ROLES.ADMIN],

  // Batches
  BATCH_VIEW:     [ROLES.ADMIN, ROLES.MANAGER, ROLES.VIEWER],
  BATCH_CREATE:   [ROLES.ADMIN, ROLES.MANAGER],
  BATCH_EDIT:     [ROLES.ADMIN, ROLES.MANAGER],
  BATCH_DELETE:   [ROLES.ADMIN],

  // Inventory
  INVENTORY_VIEW:   [ROLES.ADMIN, ROLES.MANAGER, ROLES.VIEWER],
  INVENTORY_ADJUST: [ROLES.ADMIN, ROLES.MANAGER],

  // Dashboard
  DASHBOARD_VIEW: [ROLES.ADMIN, ROLES.MANAGER, ROLES.VIEWER],

  // Alerts
  ALERT_VIEW:    [ROLES.ADMIN, ROLES.MANAGER, ROLES.VIEWER],
  ALERT_RESOLVE: [ROLES.ADMIN, ROLES.MANAGER],
};
