export interface Product {
  id: string; // Auto-generated by backend, e.g. PRODUCT001
  name: string;
  category: string;
  reorderLevel: number;
  unitPrice: number;
  stock?: number; // Usually returned in responses or update
}

export interface Batch {
  id?: string;
  productId: string;
  productName?: string;
  batchNumber: string;
  quantity: number;
  remainingQuantity?: number;
  manufactureDate: string;
  expiryDate: string;
  supplierId: number;
  locationId: number;
  purchasePrice: number;
  receivedDate?: string; // Might be mapped from backend or not needed
  status?: 'FRESH' | 'ACTIVE' | 'EXPIRING_SOON' | 'EXPIRED' | 'SPOILED' | 'RECALLED'; // Computed frontend side or returned by backend
  locationCode?: string;
  supplierName?: string;
}

export interface Supplier {
  id?: number;
  name: string;
  contactEmail: string;
  phone: string;
  rating?: number;
}

export interface Location {
  id?: number;
  warehouse: 'FREEZER' | 'DRY' | 'COLD' | string;
  section: string;
  shelf: string;
  capacity: number;
  currentOccupancy?: number;
  locationCode?: string;
}

export interface Notification {
  id: number | string;
  message: string;
  type: string;
  status: string;
  createdAt: string;
  isRead: boolean;
  targetRole: string;
  read?: boolean;
}

export interface Reorder {
  id: string;
  productId: string;
  quantity: number;
  status: string;
  createdAt: string;
}

export interface LowStockSupplier {
  productId: string;
  productName: string;
  currentStock: number;
  reorderLevel: number;
  supplierId: number | null;
  supplierName: string | null;
  supplierEmail: string | null;
  supplierPhone: string | null;
}

export interface InventoryAdjustment {
  id: string;
  productId: string;
  batchId?: string;
  type: 'IN' | 'OUT' | 'ADJUSTMENT';
  quantity: number;
  reason: string;
  date: string;
  user: string;
}

export interface DashboardStats {
  totalProducts: number;
  totalBatches: number;
  lowStockItems: number;
  activeAlerts: number;
  totalSuppliers: number;
  pendingReorders: number;
  warehouseCount: number;
  expiringSoon: number;
  recentActivity: {
    id: string;
    description: string;
    timestamp: string;
    type: 'ALERT' | 'INVENTORY' | 'SYSTEM';
  }[];
}

export interface Alert {
  id: string;
  productName: string;
  currentStock: number;
  severity: 'INFO' | 'WARNING' | 'CRITICAL';
  createdAt: string;
  resolved: boolean;
}

export type Permission =
  | 'PRODUCT_MODULE_ACCESS'
  | 'SUPPLIER_MODULE_ACCESS'
  | 'BATCH_MODULE_ACCESS'
  | 'LOCATION_MODULE_ACCESS'
  | 'QR_MODULE_ACCESS'
  | 'USER_MANAGEMENT_ACCESS'
  | 'PRODUCT_READ'
  | 'PRODUCT_CREATE'
  | 'PRODUCT_UPDATE'
  | 'PRODUCT_DELETE'
  | 'PRODUCT_UPDATE_STOCK'
  | 'SUPPLIER_READ'
  | 'SUPPLIER_CREATE'
  | 'SUPPLIER_UPDATE'
  | 'SUPPLIER_DELETE'
  | 'SUPPLIER_ASSIGN_PRODUCT'
  | 'SUPPLIER_UPDATE_RATING'
  | 'BATCH_READ'
  | 'BATCH_CREATE'
  | 'BATCH_UPDATE'
  | 'BATCH_ALLOCATE'
  | 'BATCH_SPOIL'
  | 'BATCH_RECALL'
  | 'LOCATION_READ'
  | 'LOCATION_CREATE'
  | 'LOCATION_ASSIGN_BATCH'
  | 'LOCATION_MOVE_BATCH'
  | 'USER_READ'
  | 'USER_CREATE'
  | 'USER_UPDATE'
  | 'USER_DELETE';

export interface User {
  id?: string | number;
  username: string;
  role: string;
  status: 'ACTIVE' | 'INACTIVE';
  email?: string;
  locked?: boolean;
  moduleVisibility?: string[];
  permissions?: Permission[];
  temporaryPassword?: string;
  firstLogin?: boolean;
}

export interface Customer {
  id?: string | number;
  name: string;
  email: string;
  phone: string;
  joinDate?: string;
  status: 'ACTIVE' | 'INACTIVE';
}

export interface Role {
  id?: string | number;
  name: string;
  permissions: string[];
  modules: string[];
}

export interface QRCodeData {
  id: string;
  qrCodeId: string;
  batchId: number | string;
  qrImageUrl: string;
  scanUrl: string;
  status: 'ACTIVE' | 'EXPIRED';
  createdAt: string;
}
